swagger.yaml

👉  https://github.com/getlago/lago/issues/99
When a billing period is over, users don’t want to invoice straight away.
They want a defined number of days to:
- Collect delayed events for usage
- Adjust invoice amounts for items
The goal of this PR is to be able to support these changes:
- `invoice_grace_period` on organization
- `invoice_grace_period` on customer
- `status` and `payment_status` on invoice
- filter `status` parameter on `GET invoices` endpoint
- restriction on downloading draft invoice file
- `refresh` invoice endpoint
- `finalize` invoice endpoint

feat(grace_period): Add documentation

---

swagger.yaml

👉  https://github.com/getlago/lago/issues/179
As a user, I want to be able to delete a billable metric that is linked to a subscription in case of a change of pricing (e.g. we no longer charge customers based on the number of API calls).
Once deleted, the corresponding charges will be removed from the plans and from all draft invoices.
Deleted metrics will still be included in past invoices (i.e. finalized invoices).
The goal of this PR is to add on the billable metric response:
- `active_subscriptions_count`
- `draft_invoices_count`
It also removes the 405 response from the delete query
These fields are used to know the impact of deleting billable metric.

feat(delete_bm): Update response and tests for billable metric deletion

---

swagger.yaml

Currently, there is no way to delete objects linked to a subscription. This can be a real limitation during PoCs and onboarding, as users have to ping us to delete customers.
The goal of this feature is to be able to soft-delete a customer linked to an active or terminated subscription.
This PR adds the descriptions of the new customer destroy route

feat(delete_customer) Add customer delete route

---

swagger.yaml

Currently, there is no way to delete objects linked to a subscription. This can be a real limitation during PoCs and onboarding, as users have to ping us to delete plans.
The goal of this feature is to be able to soft-delete a plan linked to an active or terminated subscription.
The goal of this PR is to add two counters in the plan response:
- `active_subscription_count`
- `draft_invoice_count`

feat(delete_plan): Add subscription and invoice counters to plans

---

swagger.yaml

Currently, there is no way to delete objects linked to a subscription. This can be a real limitation during PoCs and onboarding, as users have to ping us to delete customers.
The goal of this feature is to be able to soft-delete a customer linked to an active or terminated subscription.
This PR remove the `HTTP 405` errors on delete customer and delete coupons actions

feat(delete_customer): Remove 405 error from customer, add_on and coupon destroy

---

swagger.yaml

👉  https://github.com/getlago/lago/issues/149
Fintech companies want to deduct fees as transactions occur. They need to charge their customers instantly and report those fees in the invoice issued at the end of the billing period.
Example: 0.5% charge on FX transfers. When the customer makes a transfer of $100, they are immediately charged $0.5 (automatically deducted from their wallet). The corresponding fee is included in the invoice sent to the customer at the end of the billing period.
This PR documents a new route to retrieve a single fee via the API (`GET /api/v1/fees/:id`)
Related to https://github.com/getlago/lago-api/pull/866

feat(instant_charge): Add API route to show a fee

---

swagger.yaml

Plans edition has some issue if you update some properties of a billable metric, especially if you change groups definition or aggregation type :
"After the billable metric edition, new dimensions are created with new group_id that do not match the ones in the plans already defined"
This PR exposes a new `plans_count` field in the `BillableMetric` response type to let the API users know if the BM is editable.
Related to https://github.com/getlago/lago-api/pull/914

feat(bm): Expose count of attached plans

---

swagger.yaml

👉  https://getlago.canny.io/feature-requests/p/instantly-charge-the-customer-when-an-event-is-processed
Fintech companies want to deduct fees as transactions occur. They need to charge their customers instantly and report those fees in the invoice issued at the end of the billing period.
Example: 0.5% charge on FX transfers. When the customer makes a transfer of $100, they are immediately charged $0.5 (automatically deducted from their wallet). The corresponding fee is included in the invoice sent to the customer at the end of the billing period.
This PR adds the documentation for the new `POST api/v1/events/estimate_fees` route
Related to https://github.com/getlago/lago-api/pull/923

feat(instant_charge): documentation for event estimate fees

---

swagger.yaml

Add quotes to "example". This is required change to add Spectral validator.
Related issue:
- #30
Back ported from https://github.com/getlago/lago-openapi/pull/29.
Add quotes commands:
```zsh
cat "swagger.yaml" | python3 "add_quotes.py" > "openapi.yaml" && \
rm "swagger.yaml" && \
mv "openapi.yaml" "swagger.yaml"
```
Source of "add_quotes.py" file:
```python3
#!/usr/bin/env python3
import re
import sys
regex = r"^( *)type: string\n( *)example: ([^'\"].+[^'\"])$"
subst = "\\1type: string\n\\2example: '\\3'"
result = re.sub(regex, subst, sys.stdin.read(), 0, re.MULTILINE)
print(result)
```

#30 Add Spectral validator - Add quotes to examples

---

swagger.yaml

This PR removes the trailing slash from index route definition, in order to fix validation warnings
For example, `/invoices/` will be merge under `/invoice` with the existing `POST` definition.

misc: Remove trailing slash in routes

---

swagger.yaml

👉  https://getlago.canny.io/feature-requests/p/instantly-charge-the-customer-when-an-event-is-processed
Fintech companies want to deduct fees as transactions occur. They need to charge their customers instantly and report those fees in the invoice issued at the end of the billing period.
Example: 0.5% charge on FX transfers. When the customer makes a transfer of $100, they are immediately charged $0.5 (automatically deducted from their wallet). The corresponding fee is included in the invoice sent to the customer at the end of the billing period.
This PR adds:
- Definition for `GET /api/v1/fees`
- Definition for `PUT /api/v1/fees/:id`
- Add new fields definition to fees:
- lago_invoice_id
- external_subscription_id
- payment_status
- created_at
- succeeded_at
- failed_at
- refunded_at
- …

feat(instant_charge): Add definition for fees update and index

---

openapi.yaml

This PR add the missing pagination meta for index routes:
- Groups
- AddOns
- AppliedCoupons
- Customers
- Plans
- Subscriptions
- Invoices
- Wallets
- WalletTransactions
It also ensure types matches the inclusion list for InvoiceObject and AppliedCouponObject by adding two new types: `InvoiceObjectExtended`, `AppliedCouponObjectExtended`

feat(pagination): Add paginated definitions for all index actions

---

openapi.yaml

Update `InvoiceObject` definition:
- `currency`
- `fees_amount_cents`
- `coupons_amount_cents`
- `credit_notes_amount_cents`
- `sub_total_vat_excluded_amount_cents`
- `sub_total_vat_included_amount_cents`
- `prepaid_credit_amount_cents`
- `legacy`
- `amount_currency`
- `vat_amount_currency`
- `credit_amount_currency`
- `total_amount_currency`
- `amount_cents`
- `credit_amount_cents`

feat(invoice): Document refactoring on invoice amounts

---

openapi.yaml

Because of now we use `operationId`s in Lago Python client, I keep eye on it. :-)
- Converted all PascalCase `operationId`s to camelCase.
- Fix typo in `summary`
Related PR:
- https://github.com/getlago/lago-python-client/pull/142 (please, review :-) )

Fix operation ids

---

openapi.yaml

I didn't open an issue so I will explain here. FeeObject's `units` property is a string and not a number. The string contains a decimal number and the type string is used for good reason. However this will fail JSON schema tools because from their scope this is invalid.
As an enhancement we can consider a regexp string validation in this PR or another.
```json
{
"type": "string",
"pattern": "^[0-9]+.?[0-9]*$"
}
```

fix(types): Change FeeObject.units type from number to string

---

openapi.yaml
src/openapi.yaml
src/resources/subscription.yaml
src/resources/subscriptions.yaml
src/responses/NotAllowed.yaml
src/responses/_index.yaml
src/schemas/ApiErrorNotAllowed.yaml
src/schemas/Subscription.yaml
src/schemas/SubscriptionCreateInput.yaml
src/schemas/SubscriptionObject.yaml
src/schemas/SubscriptionUpdateInput.yaml
src/schemas/SubscriptionsPaginated.yaml
src/schemas/_index.yaml

Follows https://github.com/getlago/lago-openapi/pull/80 and https://github.com/getlago/lago-openapi/pull/81 and applies the same splitting logic for subscription resource

feat(subscription): Split definitions for subscription resource

---

openapi.yaml
src/openapi.yaml
src/resources/customer_current_usage.yaml
src/schemas/CustomerChargeUsageObject.yaml
src/schemas/CustomerUsage.yaml
src/schemas/CustomerUsageObject.yaml
src/schemas/_index.yaml

Follows https://github.com/getlago/lago-openapi/pull/80, https://github.com/getlago/lago-openapi/pull/81, https://github.com/getlago/lago-openapi/pull/82 and https://github.com/getlago/lago-openapi/pull/84 and applies the same splitting logic for customer usage resource

feat(customer): Add customer usage resource

---

openapi.yaml
src/openapi.yaml
src/resources/applied_coupons.yaml
src/resources/coupon.yaml
src/resources/coupons.yaml
src/resources/customer_applied_coupon.yaml
src/schemas/AppliedCoupon.yaml
src/schemas/AppliedCouponInput.yaml
src/schemas/AppliedCouponObject.yaml
src/schemas/AppliedCouponObjectExtended.yaml
src/schemas/AppliedCouponsPaginated.yaml
src/schemas/Coupon.yaml
src/schemas/CouponBaseInput.yaml
src/schemas/CouponCreateInput.yaml
src/schemas/CouponObject.yaml
src/schemas/CouponUpdateInput.yaml
src/schemas/CouponsPaginated.yaml
src/schemas/CreditObject.yaml
src/schemas/_index.yaml

Follows https://github.com/getlago/lago-openapi/pull/80, https://github.com/getlago/lago-openapi/pull/81, https://github.com/getlago/lago-openapi/pull/82, https://github.com/getlago/lago-openapi/pull/84 and https://github.com/getlago/lago-openapi/pull/85 and applies the same splitting logic for coupon resource

feat(coupon): Add coupon resources

---

src/schemas/CustomerObject.yaml

- `phone` has been lost during the schemas split

fix(customers): get back phone number

---

openapi.yaml
src/schemas/CustomerObject.yaml
src/schemas/CustomerObjectExtended.yaml

1. I’m adding taxes to a customer
2. I’m adding a subscription generating a invoice
3. When I GET this invoice, the response do not displays invoice.customer.taxes; BUT
4. In the documentation on [`[Retrieve an invoice](https://docs.getlago.com/api-reference/invoices/get-specific)`](https://docs.getlago.com/api-reference/invoices/get-specific) we display this information 
1. I’m adding taxes to a customer
2. I’m adding a subscription generating a invoice
3. When I GET this invoice, the response do not displays invoice.customer.taxes; BUT
4. In the documentation on [`[Retrieve an invoice](https://docs.getlago.com/api-reference/invoices/get-specific)`](https://docs.getlago.com/api-reference/invoices/get-specific) we should not display this information

fix(tax): Make sure customer taxes only appears on customer routes

---

openapi.yaml
src/resources/subscriptions.yaml

Update the GET /subscriptions endpoint with the correct behavior

fix(subscriptions) return active subscriptions by default

---

openapi.yaml
src/schemas/CustomerCreateInput.yaml
src/schemas/CustomerObject.yaml
src/schemas/InvoiceObject.yaml
src/schemas/OrganizationObject.yaml
src/schemas/OrganizationUpdateInput.yaml

This PR updated the openapi schema for 3 models
Invoice
- New net_payment_term attribute (read)
- New payment_due_date attribute (read) 
Customer
- New net_payment_term attribute (write and read)
Organization
- New net_payment_term attribute (write and read)

feat: expose new net-payment and payment_due_date attributes

---

openapi.yaml
src/schemas/AddOnBaseInput.yaml
src/schemas/AddOnObject.yaml
src/schemas/InvoiceOneOffCreateInput.yaml
src/schemas/TaxObject.yaml

👉  [https://getlago.canny.io/feature-requests/p/create-several-tax-rates](https://getlago.canny.io/feature-requests/p/create-several-tax-rates)
After the delivery of the "multiple taxes" feature https://github.com/getlago/lago-api/pull/1104, we now want to be able to define taxes at add ons level.
This PR adds the ability to assign taxes on add on create/update.

feat(tax): Add taxes to add ons

---

openapi.yaml
src/schemas/ChargeProperties.yaml

👉  https://getlago.canny.io/feature-requests/p/apply-price-floorcap-on-transactions
Fintech users want to be able to cap a transaction to a maximum amount or to flour it to a minimum amount.
This feature will apply this logic to the `percentage` charge model.
This PR documents the `per_transaction_max_amount`/`per_transaction_min_amount` fields for charge model properties

feat(charge): Document min/max per transaction amount for percentage charge model

---

openapi.yaml
src/openapi.yaml
src/schemas/EventObject.yaml

An issue with the generated ruby client has been identified in the event payload.
The generated code was not accepting additional attributes in the properties payload.
This PR is an attempt to fix it by defining the type of accepted additional property keys

fix: event additional properties for client generation

---

openapi.yaml
src/schemas/EventInput.yaml

Similar to https://github.com/getlago/lago-openapi/pull/144
An issue with the generated ruby client has been identified in the event payload.
The generated code was not accepting additional attributes in the properties payload.
This PR is an attempt to fix it by defining the type of accepted additional property keys

fix: event input properties

---

openapi.yaml
src/schemas/EventInput.yaml

Similar to https://github.com/getlago/lago-openapi/pull/144
An issue with the generated ruby client has been identified in the event payload.
The generated code was not accepting additional attributes in the properties payload.
This PR is an attempt to fix it by defining the type of accepted additional property keys

fix: event payload issue

---

openapi.yaml
src/schemas/_index.yaml

Adds missing schemas to `src/schemas/_index.yaml`. 
Using the current `openapi.yaml` file we were unable to generate a properly typed openapi SDK (using `openapi-typescript-codegen`). 
Some `$ref` appeared to be malformated (eg. `$ref: '#/paths/~1webhook_endpoints/post/responses/200/content/application~1json/schema/properties/webhook_endpoint'`  at openapi.yaml:2218), leading to buggy generated imports.

fix: adds missing schemas to _index.yaml

---

openapi.yaml
src/schemas/CouponObject.yaml

Call to `GET /v1/api/coupons/:code` is missing the `terminated_at` value
This PR is adding the missing field in the `CouponObject`

fix(coupon): Add missing coupons#terminated_at

---

openapi.yaml
src/resources/subscription.yaml

We want to improve the way we are overriding a plan. Without working as a duplicate, by adding the logic for managing parent and children of plans.
The goal of this PR is to add the endpoint `GET /api/v1/subscriptions/:external_id`.

feat(override-plan): Ability to fetch a single subscription

---

openapi.yaml
src/schemas/AddOnBaseInput.yaml
src/schemas/AddOnObject.yaml
src/schemas/ChargeObject.yaml
src/schemas/FeeObject.yaml
src/schemas/GroupPropertiesObject.yaml
src/schemas/InvoiceOneOffCreateInput.yaml
src/schemas/PlanCreateInput.yaml
src/schemas/PlanObject.yaml
src/schemas/PlanUpdateInput.yaml

Add a custom name to display on invoice for subscription fee and charges
When generating an invoice, don't display the name of the plan or the name of the billable metrics to the customer.

feat(invoice_display_name) Add invoice display name

---

openapi.yaml
src/resources/events_batch.yaml

Lago route `POST /api/v1/events/batch` is a misleading route as it does not offers a real batch feature but instead offers a way to send and event for simultaneous subscriptions.
It appears that this route is not used at all on the Lago cloud instance. Lago teams decided to deprecate this route in favor of a future batch route allowing users to send multiple events at the same time.
This PR simply mark the route as `deprecated`. It will be removed in a future PR.

misc(event): Deprecate batch route

---

openapi.yaml
src/openapi.yaml
src/resources/customer_past_usage.yaml
src/schemas/CustomerChargeUsageObject.yaml
src/schemas/CustomerPastUsage.yaml
src/schemas/CustomerUsageObject.yaml
src/schemas/_index.yaml

Some of our users want to retrieve usage in the past. The main problem they are facing is that at the beginning of a new period, they cannot compute usage in third party systems, or see if everything went well as usage for the past period has been removed.
This PR documents the new route to retrieve the past usage

feat(past_usage): Documents new API route

---

openapi.yaml
src/schemas/OrganizationObject.yaml
src/schemas/OrganizationUpdateInput.yaml

Before, it was not possible to adapt document number. With this feature it will be enabled to switch between `per_customer` and `per_organization` document numbering logic. Also, it will be possible to edit number prefix.
This PR adds support for new document numbering fields

feat (document-numbering): add support for new document numbering fields

---

src/schemas/InvoiceObject.yaml

I observed in a webhook that an invoice can have a status of voided, yet the spec (and thus clients) don't support it.

Modify InvoiceObject spec to make voided status an option

---

openapi.yaml
src/schemas/ChargeProperties.yaml
src/schemas/CustomerChargeGroupedUsageObject.yaml
src/schemas/CustomerChargeGroupsUsageObject.yaml
src/schemas/CustomerChargeUsageObject.yaml
src/schemas/FeeObject.yaml
src/schemas/_index.yaml

Some customers have requested a way to group usage fees on an invoice using an event property. The same charge model properties should be applied to each group. The logic will only apply to `standard` charge model.
This PR adds the OpenAPI documentation for all new fields related to the feature

feat(grouped-by): Add documentation

---

src/schemas/SubscriptionUpdateInput.yaml

Imagine you are updating a subscription and want to remove the `ends_at` date.
Right now this doesn't work correctly: Settings `ends_at` to null in Java code will omit `ends_at` from the request all together. The cause is that generated client specifies `@JsonInclude(Include.USE_DEFAULTS)` on the field, which will by default omit any null values from the request.
We need to override this for this specific field. Setting it to required in the spec will change the annotation to `@JsonInclude(Include.ALWAYS)` , which will cause it be serialised in the request, even if it's value is null.

Update openapi.yaml to make sure ending_at is always serialized in request

---

openapi.yaml
src/schemas/MinimumCommitmentInput.yaml
src/schemas/MinimumCommitmentObject.yaml
src/schemas/PlanCreateInput.yaml
src/schemas/PlanObject.yaml
src/schemas/PlanOverridesObject.yaml
src/schemas/PlanUpdateInput.yaml
src/schemas/_index.yaml

👉  https://getlago.canny.io/feature-requests/p/set-minimum-spend-for-subscriptions
As a user, I want to define the minimum spend that applies to the customer's plan. Consider the following monthly plan:
- Subscription fee = $50 per month (in arrears);
- Usage-based charge = $10 per unit per month (in arrears); and
- Monthly minimum spend = $100.
If at the end of the month, the customer has consumed 3 units, their total invoice will be: $50 + 3 * $10 = $80 + $20 (true-up fee) = $100.
This PR adds minimum commitment to plan and plan overrides.

feat(minimum-commitment): Add minimum commitment

---

openapi.yaml
src/schemas/PlanOverridesObject.yaml
src/schemas/_index.yaml

Adds missing schemas to `src/schemas/_index.yaml`.
Fixes inverted ref : `MinimumCommitmentInput` instead of `MinimumCommitmentObject`
Using the current `openapi.yaml` file we were unable to generate a properly typed openapi SDK (using openapi-typescript-codegen).
Here is our openapi codegen config (from package.json): 
```
"lago-sdk": "openapi --input ./openapi.yaml --output src/providers/lago/lago.sdk --name LagoClient --client axios --useOptions --useUnionTypes",
```
Then running `tsc --noEmit` makes it easy to identify errors in the schema, maybe this could be a step in your CI upon schema change?

fix(openapi-schema): fix MinimumCommitmentObject ref

---

openapi.yaml
src/schemas/InvoiceObject.yaml

Currently, we generate `sequential_id` upon invoice finalization. When the invoice is draft `sequential_id` could be nil.
We have to make this field optional in api response.

fix: mark sequential_id as optional

---

openapi.yaml
src/resources/billable_metric_groups.yaml
src/schemas/BillableMetricBaseInput.yaml
src/schemas/BillableMetricFilterInput.yaml
src/schemas/BillableMetricFilterObject.yaml
src/schemas/BillableMetricGroup.yaml
src/schemas/BillableMetricObject.yaml
src/schemas/ChargeFilterInput.yaml
src/schemas/ChargeFilterObject.yaml
src/schemas/ChargeObject.yaml
src/schemas/CustomerChargeFiltersUsageObject.yaml
src/schemas/CustomerChargeGroupedUsageObject.yaml
src/schemas/CustomerChargeGroupsUsageObject.yaml
src/schemas/CustomerChargeUsageObject.yaml
src/schemas/FeeObject.yaml
src/schemas/PlanCreateInput.yaml
src/schemas/PlanObject.yaml
src/schemas/PlanOverridesObject.yaml
src/schemas/PlanUpdateInput.yaml
src/schemas/_index.yaml

Lago is not currently supporting more than 2 levels of event grouping (parent → children)
The goal of this feature is to allow more flexibility of event grouping by allowing an unlimited level of grouping and making it easier to define default charge properties for events based on their properties.
This PR add the documentation for the new filter in both input and output objects

feat(filter): Filter documentation

---

openapi.yaml
src/resources/wallet_transactions.yaml
src/schemas/WalletTransactionObject.yaml

We want to differentiate a free wallet transaction vs. a paid wallet transaction.
And be able to void some wallet transactions.
This PR aims to add the `transaction_status` field for Wallet.

feat(wallet): Add transaction_status to wallet object

---

openapi.yaml
src/resources/wallet_transactions.yaml
src/schemas/WalletTransactionObject.yaml

We want to differentiate a free wallet transaction vs. a paid wallet transaction.
And be able to void some wallet transactions.
This PR aims to rename:
- `paid` to `purchased`
- `offered` to `granted`
for the `transaction_status` field for Wallet.

feat(wallet): Rename transaction statuses for wallet

---

openapi.yaml
src/resources/wallet_transactions.yaml
src/schemas/WalletTransactionCreateInput.yaml
src/schemas/WalletTransactionObject.yaml

We want to differentiate a free wallet transaction vs. a paid wallet transaction.
And be able to void some wallet transactions.
This PR aims to create a voided wallet transaction.

feat(wallet): Add voided_credits to WalletTransaction

---

openapi.yaml
src/schemas/WalletCreateInput.yaml
src/schemas/WalletRecurringTransactionRule.yaml
src/schemas/WalletUpdateInput.yaml

After the release of real-time wallet version 1, some customers have expressed concerns about odd or missing behaviors.
The goal of this PR is to rename `Wallet#rule_type` into `Wallet#trigger`.

feat(wallet): Rename wallet rule_type into trigger

---

openapi.yaml
src/parameters/lago_invoice_id.yaml

Use right quotation in params section. Invalid quotation can lead to encoding issues in the browser

fix(invoice-params): use right quotation

---

openapi.yaml
src/schemas/WalletCreateInput.yaml
src/schemas/WalletRecurringTransactionRule.yaml
src/schemas/WalletUpdateInput.yaml

👉 https://getlago.canny.io/feature-requests/p/define-a-target-balance-to-reach-for-recurring-top-up
We want to allow users to top-up their wallets to reach a specific target balance.
We can currently define a fixed top-up but we want to add the ability to specify a dynamic top-up (target balance to reach).
The goal of this PR is to add:
- `granted_credits`
- `paid_credits` 
- `method`
- `target_ongoing_balance`
- `started_at`
to `recurring_transaction_rule`

feat(wallet): Add fields to recurring_transaction_rule

---

openapi.yaml
src/schemas/EventInput.yaml
src/schemas/EventObject.yaml

fixes https://github.com/getlago/lago-javascript-client/issues/43
This PR improves the definition of `events#properties` payload for input and output to make clear that value types could be `string`, `integer` or `number`

fix: Improve event#properties definition

---

openapi.yaml
src/resources/invoices.yaml
src/schemas/InvoiceObject.yaml

👉 https://getlago.canny.io/feature-requests/p/regroup-invoices-to-generate-one-payment-intent
We want to be able to group invoices to generate one payment.
Today we don't track payment terms and do not mention whether a payment or an invoice is overdue.
The goal of this PR is to add:
- `payment_overdue`
to `invoice`

feat(dunning): Add payment_overdue to invoice

---

openapi.yaml
src/openapi.yaml

This PR adds the `api.eu` subdoamin in the list of API server

misc: Add EU cluster server in definition

---

openapi.yaml
src/schemas/EventBatchInput.yaml
src/schemas/EventInput.yaml
src/schemas/EventInputObject.yaml

This PR fixes event batch format.
It removes the `event` object for each event within the array, so instead of:
```
{
events: [
{
event: {
transaction_id: "__UNIQUE_TRANSACTION_ID_1__",
external_subscription_id: "__SUBSCRIPTION_ID_1__",
code: "__BILLABLE_METRIC_CODE__",
...
}
}
]
}
```
the correct format is:
```
{
events: [
{
transaction_id: "__UNIQUE_TRANSACTION_ID_1__",
external_subscription_id: "__SUBSCRIPTION_ID_1__",
code: "__BILLABLE_METRIC_CODE__",
...
}
]
}
```

Fix EventBatchInput format

---

openapi.yaml
src/schemas/CustomerChargeUsageObject.yaml

The `weighted_sum_agg` and `latest_agg` were missing into the `CustomerChargeUsageObject`.
These missing values cause errors during the deserialization process.

Add missing value for aggregation_type in CustomerChargeUsageObject

---

openapi.yaml
src/resources/overdue_balances.yaml
src/schemas/GrossRevenueObject.yaml
src/schemas/InvoiceCollectionObject.yaml
src/schemas/OverdueBalanceObject.yaml
src/schemas/OverdueBalances.yaml
src/schemas/_index.yaml

👉 https://getlago.canny.io/feature-requests/p/regroup-invoices-to-generate-one-payment-intent
We want to be able to group invoices to generate one payment.
Today we don't track payment terms and do not mention whether a payment or an invoice is overdue.
The goal of this PR is to add an analytics endpoint for fetching overdue balances per month and per currency at the customer or organization level.

feat(analytics): Add overdue balance endpoint

---

openapi.yaml
src/openapi.yaml

As announced a few months ago, this release updates the event ingestion process and removes deprecated API fields.
Changes include:
The new dimension system based on filters is already available. It allows users to create billable metrics with more than two dimensions, and makes it easier to create charges based on custom event properties. The former dimension system based on groups is now permanently removed from the Lago API ([see all changes](https://docs.getlago.com/guide/migration/migration-to-v1.2.0#1-transition-from-group-to-filters)).
Events that only include external_customer_id will no longer be taken into account when aggregating usage ([learn more](https://docs.getlago.com/guide/migration/migration-to-v1.2.0#2-mandatory-external-subscription-id-field-in-event-payloads)). This …

misc(version): Bump to v1.7.0

---

openapi.yaml
src/schemas/ChargeObject.yaml
src/schemas/PlanCreateInput.yaml
src/schemas/PlanObject.yaml
src/schemas/PlanUpdateInput.yaml

Document `charge.regroup_paid_fees` added [here](https://github.com/getlago/lago-api/pull/2232)

feat(charges): Add Charge.regroup_paid_fees attribute

---

openapi.yaml
src/schemas/EventInput.yaml

Following https://github.com/getlago/lago-openapi/pull/249 I'm removing the `allOf` to refer to the EventInputObject schema in EventInput.
Today, the batch `EventBatchInput` has the complete definition of an event, while the `EventInput` references `#/components/schemas/EventBatchInput/properties/events/items`.
This PR changes so `EventInput` has the definition of an event and `EventBatchInput` references it.
_"What's the difference"_ you're asking. I dunno but I'm hoping it's going to make a difference for [openapi-generator](https://github.com/OpenAPITools/openapi-generator) when generating client. Also, it feels a little better.
Note: make sure you expend the diff of `openapi.yaml`

Remove `allOf` to reference EventInput in /event endpoint

---

package-lock.json
package.json

- `@stoplight/spectral` is deprecated, we should now use `@stoplight/spectral-cli`
- Fix https://github.com/getlago/lago-openapi/security/dependabot/11 and https://github.com/getlago/lago-openapi/security/dependabot/6

misc(dependencies): Update dependencies

---

openapi.yaml
src/schemas/FeeObject.yaml

For some customers some amounts are not enough precise as Lago convert fees to `amount_cent`.
Add precise amounts to fee object.

Add precise amounts to fee object

---

openapi.yaml
src/resources/customer_portal_url.yaml

👉  [https://getlago.canny.io/feature-requests/p/{{FEATURE_SLUG}}](https://getlago.canny.io/feature-requests/p/add-features-to-the-customer-portal)
We got feedback that this portal is too limited in terms of features and information. Why?
**1st reason:** the number of information displayed is limited
**2nd reason:** the end user cannot take actions out of it (change info, add payment method)
**3rd reason:** the UI and display is not customizable
The goal of this PR is to make accessible to all our users (free and premium) the customer portal URL.

feat(customer-portal): Remove premium restriction

---

openapi.yaml
src/schemas/CustomerBaseObject.yaml
src/schemas/CustomerCreateInput.yaml

We currently only create Lago customers as **companies**, but there is a need to support both **companies** and **individuals**. This change is motivated by scenarios where customers may be a mix of B2B and B2C, and where external integrations require handling both **Contacts** and **Companies**.
To address this, we are introducing a new field, `customer_type`, to distinguish whether a customer is a **company** or an **individual**. Existing customers will remain unaffected with `customer_type` set to the default `nil`. 
This PR adds `firstname`, `lastname` and `customer_type` to the customer object and create input.

feat(customer-type): Add customer type, firstname and lastname to customer

---

openapi.yaml
src/schemas/CouponCreateInput.yaml

Expiration field on coupon has not_null constraint in the DB, with no default value, so this field should be required in the request

Fix: Specify expiration on coupon as required at coupon create input schema

---

openapi.yaml
src/openapi.yaml
src/resources/subscription_lifetime_usage.yaml
src/schemas/LifetimeUsage.yaml
src/schemas/LifetimeUsageInput.yaml
src/schemas/LifetimeUsageObject.yaml
src/schemas/LifetimeUsageThresholdObject.yaml
src/schemas/_index.yaml

AI companies want their users to pay before the end of a period if usage skyrockets. The problem being that self-serve companies can overuse their API without paying, triggering lots of costs on their side.
This PR adds new routes to fetch and update the lifetime usage of a subscription

feat(ProgressiveBilling): Expose lifetime usage GET and PUT

---

openapi.yaml
src/openapi.yaml

Change the region part in the url so instead of this format:
`{{region}}.getlago.com`
we'll have: `api.{{region}}getlago.com`

misc(region): Change the region part in the url

---

openapi.yaml
src/schemas/ChargeObject.yaml
src/schemas/EventInputObject.yaml
src/schemas/EventObject.yaml
src/schemas/PlanCreateInput.yaml
src/schemas/PlanUpdateInput.yaml

AI, CPaaS and Fintech customers can apply a price to a unit that fluctuates over time. Currently Lago does not support this usecase.
This PR is related to https://github.com/getlago/lago-api/pull/2610.
It documents the new `precise_total_amount_cents` in input and result payloads on `POST /api/v1/events` and `POST /api/v1/batch_events`

feat(DynamicPricing): Document Event#precise_total_amount_cents

---

openapi.yaml
src/schemas/SubscriptionObject.yaml

The goal of this PR is to add current billing period dates at the subscription level.

feat: Add current billing period dates

---

openapi.yaml
src/openapi.yaml

This PR addresses an issue where an empty string in the region variable resulted in an incorrect base URL being generated, specifically https://api. {region}getlago.com/api/v1 instead of https://api.getlago.com/api/v1.
The previous configuration for the region variable used an empty string as the default, which caused the incorrect URL structure. The fix involves adjusting the default value of the region variable and ensuring that the resulting URL is properly constructed as https://api.getlago.com/api/v1 when no region is specified.

fix: Fix issue with incorrect base URL generation due to empty string in region variable

---

openapi.yaml
src/schemas/FeeObject.yaml

Related to https://github.com/getlago/lago-api/pull/2710
Documents the new `fees#charge_id` field

feat(fee): Expose charge_id in REST API

---

openapi.yaml
src/openapi.yaml
src/resources/billable_metric_evaluate_expression.yaml
src/schemas/BillableMetricBaseInput.yaml
src/schemas/BillableMetricEvaluateExpressionInput.yaml
src/schemas/BillableMetricEvaluateExpressionResult.yaml
src/schemas/BillableMetricObject.yaml
src/schemas/_index.yaml

This PR is related to https://github.com/getlago/lago-api/pull/2704
It exposes:
- The new `expression` field on billable metric input and output payloads
- The new `POST /api/v1/billable_metrics/evaluate_expression` api end-point

feat(felixible aggregation): Expose expression in API

---

openapi.yaml
src/schemas/BillableMetric.yaml
src/schemas/BillableMetricObject.yaml
src/schemas/BillableMetricObjectExtended.yaml
src/schemas/_index.yaml

For some performance reason, it was decided to deprecate 3 counter fields in the response payload for `/api/v1/billable_metrics` API end-point.
The deprecated fields will be:
- active_subscriptions_count
- draft_invoices_count
- plans_count
To avoid duplicating object definition, the existing `BillableMetricObject` has been kept (with the deprecated fields waiting for removal) and a new `BillableMetricObjectExtended` was added to handle the response to `/api/v1/billable_metrics/:id` were the fields are not deprecated

misc: Deprecate counters at billable metric index level

---

openapi.yaml
src/resources/invoices.yaml

feat(export invoices): extend GET /invoices by amount and metadata

---

openapi.yaml
src/schemas/BillingPeriodObject.yaml
src/schemas/InvoiceObject.yaml

Related to https://github.com/getlago/lago-api/pull/3064

feat: Expose billing periods with invoice object

---

openapi.yaml
src/schemas/PaymentRequestCreateInput.yaml

Fix for https://github.com/getlago/lago-go-client/issues/223
The API is expecting an `external_customer_id`, but the documentation is inconsistent, as it exposes a `customer_external_id` field

fix(paymentRequest): requires an external_customer_id

---

openapi.yaml
src/openapi.yaml
src/resources/wallet_transaction.yaml

New endpoint to retrieve a single wallet transactions by ID.
The feature: https://github.com/getlago/lago-api/pull/3119

feat(wallet): GET /wallet_transactions/{lago_id}

---

openapi.yaml
src/openapi.yaml
src/resources/customer.yaml

In the `/customers` endpoints, the path parameter `external_customer_id` was named `external_id` for 2 endpoints.
In Postman, you'd get 2 directories, making you think it was a different parameter.

fix(customer): Rename external_id to external_customer_id for consistency

---

openapi.yaml
src/resources/customer_current_usage.yaml

This PR introduces an optional `apply_taxes` query parameter to the 
GET `/api/v1/customers/{external_customer_id}/current_usage` endpoint. 
With this change, API consumers can now specify whether taxes should be applied when calculating a customer’s current usage. If the parameter is omitted or provided as null, it defaults to true (taxes applied), maintaining the existing behavior.

feat: add apply_taxes to current usage

---

src/schemas/EventInputObject.yaml

This PR adds a warning about the handling of the idempotency logic in Clickhouse that differs from the one in Postgres

misc(event): Add warning about clickhouse idempotency logic

---

openapi.yaml
src/schemas/BillingEntityCreateInput.yaml
src/schemas/BillingEntityObject.yaml
src/schemas/BillingEntityUpdateInput.yaml
src/schemas/CustomerCreateInput.yaml
src/schemas/InvoiceBaseObject.yaml
src/schemas/WalletCreateInput.yaml
src/schemas/WalletUpdateInput.yaml

fixes the following errors:
```
validating openapi.yaml...
[1] openapi.yaml:5408:11 at #/components/schemas/BillingEntityObject/properties/document_number_prefix/nullable
Property `nullable` is not expected here.
5406 |   example: ABC-123
5407 |   description: The prefix used in document numbers for this billing entity
5408 |   nullable: true
5409 | finalize_zero_amount_invoice:
5410 |   type: boolean
Error was generated by the struct rule.
[2] openapi.yaml:5417:11 at #/components/schemas/BillingEntityObject/properties/invoice_footer/nullable
Property `nullable` is not expected here.
5415 |   example: Thank you for your business
5416 |   description: The footer text to be displayed on invoices for this billing entity
5417 |   nullable: true
5418 | invoice_grace_period:
5419 |   type: …
```

fix(build) Openapi 3.1 supports null type instead of nullable

---

openapi.yaml
src/resources/subscription.yaml

This query parameter was added in https://github.com/getlago/lago-api/pull/1324 but was never documented.

docs(subscription): Add `status` query param doc in 'Retrieve a subscription' endpoint

---

openapi.yaml
src/resources/applied_coupons.yaml

Clients can review applied coupons using the relevant endpoint: https://getlago.com/docs/api-reference/coupons/get-all-applied. However, since there is no way to filter by coupon code, clients must page through all results to find redemptions for a specific coupon.
This PR documents the `coupon_code` filter added to the `GET /api/v1/applied_coupons` endpoint in https://github.com/getlago/lago-api/pull/3782.

feat(coupons): Add `coupon_code` filter for "List all applied coupons"

---

openapi.yaml
src/resources/payments.yaml

This issue fixes the ticket [ISSUE-909](https://linear.app/getlago/issue/ISSUE-909/update-filter-for-list-all-payments-endpoint-docs).
It changes the param name for `List all payments` from `lago_invoice_id` to `invoice_id`. 
Reference:[API param](https://github.com/getlago/lago-api/blob/43713815280fc8cce1d9cdff042067125654b84f/app/controllers/api/v1/payments_controller.rb#L64)

fix(issue-909):fix param name for list all payments

---

openapi.yaml
src/schemas/ChargeProperties.yaml

This PR is related to https://github.com/getlago/lago-api/pull/3790
It updates the `ChargeProperties` object:
- Mark `group_by` field as deprecated
- Document the new `pricing_group_keys` and removes the charge model limitation

feat(pricing_group_keys): Update documentation

---

openapi.yaml
src/resources/invoice_void.yaml
src/schemas/InvoiceVoidInput.yaml

Extend Void Invoice endpoint with credit-note workflow
Updated /invoices/{lago_id}/void doc:
Default behaviour unchanged – invoice must be finalized & payment NOT succeeded.
If generate_credit_note is sent, validation is bypassed: invoice is forcibly voided, credit note(s) created.
Remainder (when partial refund / credit) is placed on an auto-voided second credit note for bookkeeping.

feat: add params to void invoice

---

openapi.yaml
src/schemas/BillingEntityUpdateInput.yaml

Recently update API to allow reseting the logo value of a Billing entity https://github.com/getlago/lago-api/pull/3957
Better mention it in doc

doc: null value for logo resets it

---

openapi.yaml
src/openapi.yaml
src/resources/event_estimate_instant_fees.yaml
src/resources/events_batch_estimate_instant_fees.yaml
src/schemas/EventBatchEstimateInstantFeesInput.yaml
src/schemas/EventEstimateInstantFeesInput.yaml
src/schemas/FeeEstimateObject.yaml
src/schemas/FeesEstimate.yaml
src/schemas/_index.yaml

This PR adds the missing definition for
- `POST   /api/v1/events/estimate_instant_fees`
- `POST  /api/v1/events/batch_estimate_instant_fees`

misc(event): Add missing definitions for estimate instant routes

---

openapi.yaml
src/schemas/CreditNoteErrorDetailsObject.yaml
src/schemas/CreditNoteEstimated.yaml
src/schemas/CreditNoteObject.yaml
src/schemas/_index.yaml

Fixes related to https://github.com/getlago/lago-go-client/pull/268 to align the OpenAPI schema with the REST API

fix(credit_note): Add missing payloads

---

openapi.yaml
src/schemas/FeeAmountDetails.yaml

Requested here 
https://getlago.slack.com/archives/C08FL5Y4E9H/p1752072472708829
and the value is being saved inside the `amount_details` here https://github.com/getlago/lago-api/blob/main/app/services/fees/subscription_service.rb#L58

(add):plan_amount_cents to fee-amount-details

---

openapi.yaml
src/resources/subscription.yaml
src/schemas/SubscriptionObject.yaml

https://github.com/getlago/lago-api/pull/4047 added a `on_termination_invoice` query parameter and attribute on the `DELETE /api/v1/subscriptions/:external_id` endpoint.
This PR updates the OpenAPI accordingly.

feat(subscription): Add `on_termination_invoice` to subscription

---

openapi.yaml
src/resources/customer_current_usage.yaml
src/schemas/CustomerChargeFiltersUsageObject.yaml
src/schemas/CustomerChargeGroupedUsageObject.yaml
src/schemas/CustomerChargeUsageObject.yaml
src/schemas/CustomerUsageObject.yaml

Added `projected_units` and `projected_amount_cents` to the:
1. `CustomerChargeUsageObject`
2. `CustomerChargeFiltersUsageObject`
3. `CustomerChargeGroupedUsageObject`
Also added projected_amount_cents to the main object which is: `CustomerUsageObject`.
Also changed the endpoint description, as it now returns also the projected data.

feat(api): Add projected units and projected amount cents to the customer usage models

---

openapi.yaml
src/resources/subscription.yaml
src/schemas/SubscriptionObject.yaml

https://github.com/getlago/lago-api/pull/4026 added a `refund` value to `on_termination_credit_note` parameter on the `DELETE /api/v1/subscriptions/:external_id` endpoint.
This PR updates the OpenAPI accordingly.

feat(subscription): Add `refund` to subscription's `on_termination_credit_note`

---

openapi.yaml
src/schemas/WalletTransactionObjectExtended.yaml
src/webhooks/wallet_transaction_created.yaml
src/webhooks/wallet_transaction_updated.yaml

`wallet_transaction.created` and `wallet_transaction.updated` webhooks did not contain wallet object only the wallet id.
That required an extra request to be made to fetch the wallet.
This PR adds the whole `wallet` object to `wallet_transaction.created` and `wallet_transaction.updated` webhooks.

feat(wallet-transactions): Add wallet to wallet transaction webhooks

---

openapi.yaml
src/resources/invoices.yaml

Through the API, we're currently able to filter per payment status but it's a single choice and not multiple choice — that said, user can't filter per multiple payment status (e.g. payment_status=pending,failed to retrieve all pending and failed ones in one go)
We should be able to filter invoice by a set of payment_status: `pending`, `failed`, `succeeded`.
We should be able to filter invoice by all visible status: `draft`, `finalized`, `voided`, `failed` & `pending`
https://github.com/getlago/lago-api/pull/4279

feat(invoice-filters): Add the options to query multiple statuses

---

openapi.yaml
src/schemas/FeeObject.yaml
src/schemas/WalletTransactionCreateInput.yaml
src/schemas/WalletTransactionObject.yaml

When creating a wallet transaction, the name displayed on the invoice defaults to the wallet name. However, for organizations managing multiple types of top-ups, it would be beneficial to display specific naming on invoices that corresponds to the particular transaction being made.
This is the documentation for changes introduced in https://github.com/getlago/lago-api/commit/eecb90fb60190504307c6d71337519e8fcf23a52. It adds a `name` attribute to the wallet transaction object and inputs. It also updates the description of the fees'a fields.

feat(wallet-transaction): Add a `name` to wallet transactions

---

openapi.yaml
src/schemas/ChargeModelEnum.yaml
src/schemas/ChargeObject.yaml
src/schemas/PlanCreateInput.yaml
src/schemas/PlanOverridesObject.yaml
src/schemas/PlanUpdateInput.yaml

The `charge_model` is defined in multiple places and some of them are outdated. Also the subscription creation and update were missing this property in `plan_overrides`.
This adds a re-usable `src/schemas/ChargeModelEnum.yaml` file and make sure subscription creation and update includes the `charge_model` in `plan_overrides`.

misc(charge): Make `charge_model` re-usable and add `charge_model` to subscriptions

---

openapi.yaml
src/schemas/WalletCreateInput.yaml
src/schemas/WalletRecurringTransactionRule.yaml
src/schemas/WalletUpdateInput.yaml

When creating a wallet transaction, the name displayed on the invoice defaults to the wallet name. However, for organizations managing multiple types of top-ups, it would be beneficial to display specific naming on invoices that corresponds to the particular transaction being made.
This change adds a `name` attribute to the wallet transaction recurring rule object and inputs.

feat(wallet-transaction): Add `transaction_name` to recurring transaction rules

---

openapi.yaml
src/schemas/WalletCreateInput.yaml

👉  https://getlago.canny.io/feature-requests/p/define-the-name-of-a-wallet-transaction-at-top-up
Follow up of https://github.com/getlago/lago-api/pull/4327.
This documents the possibility to provide a `name` for the wallet transactions created when creating a wallet via the `transaction_name` field.

feat(wallet): Allow to set the name of a wallet's initial transactions

---

openapi.yaml
src/schemas/FeeObject.yaml

This PR fixes the code for https://github.com/getlago/lago-openapi/pull/437
FeeObject.item.item_type description mentions Commitment as a possible value but it's not present in the possible values in the enum. 
Ticket: Pylon #3920

fix(fee): Fix item_type documentation
