getlago/lago-openapi

swagger.yaml
=> Fix #22 - Add `charges_from_date`

.github/workflows/ApiDOM-validator.yml
=> Fix #35 Replace old editor validator to ApiDOM validator

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, PULL_REQUEST_TEMPLATE.md, README.md
This PR improves the repository by adding:
- A README
- The AGPLv3 License
- A contribution guide
- A code of conduct guide
- bugs and pull request templates
=> misc: Update and fix contribution guide

.github/workflows/Spectral.yml, swagger.yaml
=> Fix #42 - Add format support for dates, uuid and emails

openapi.yaml
👉  https://getlago.canny.io/feature-requests/p/define-minimum-fees
We want to allow users to set spendings minimum on usage-based charges.
The goal of this PR is to:
- add min_amount_cents to Charge
- add lago_true_up_fee_id to Fee
- add lago_true_up_parent_fee_id to Fee
=> feat(min_charge): Ability to specify a minimum amount for a charge

openapi.yaml
Related to https://github.com/getlago/lago-api/pull/1013
=> feat(subscription): Allow plan filters on subscription index

openapi.yaml
Expose new `tax_identification_number` attribute on customer and organization model
=> feat: add tax_identification_number to customer and organization

openapi.yaml
Similar to #74 , Fixes the type of many fields from number to string.
Many were pending there, I was waiting for confirmation before adding more fixes.
=> Fix type to string

openapi.yaml, src/openapi.yaml, src/resources/event.yaml, src/resources/events.yaml, src/resources/events_batch.yaml, src/schemas/Event.yaml, src/schemas/EventBatchInput.yaml, src/schemas/EventInput.yaml, src/schemas/EventObject.yaml, src/schemas/_index.yaml
Follows https://github.com/getlago/lago-openapi/pull/80, https://github.com/getlago/lago-openapi/pull/81 and https://github.com/getlago/lago-openapi/pull/82 and applies the same splitting logic for event resource
=> feat(event): Add event resources

openapi.yaml, src/openapi.yaml, src/resources/organizations.yaml, src/schemas/Organization.yaml, src/schemas/OrganizationBillingConfiguration.yaml, src/schemas/OrganizationObject.yaml, src/schemas/OrganizationUpdateInput.yaml, src/schemas/_index.yaml
Follows https://github.com/getlago/lago-openapi/pull/80, https://github.com/getlago/lago-openapi/pull/81, https://github.com/getlago/lago-openapi/pull/82, https://github.com/getlago/lago-openapi/pull/84 and https://github.com/getlago/lago-openapi/pull/85 and applies the same splitting logic for organization resource
=> feat(organization): Add organization resource

openapi.yaml, src/openapi.yaml, src/parameters/_index.yaml, src/parameters/external_customer_id.yaml, src/parameters/external_subscription_id.yaml, src/resources/fee.yaml, src/resources/fees.yaml, src/schemas/Fee.yaml, src/schemas/FeeObject.yaml, src/schemas/FeeUpdateInput.yaml, src/schemas/Fees.yaml, src/schemas/FeesPaginated.yaml, src/schemas/_index.yaml
Follows https://github.com/getlago/lago-openapi/pull/80, https://github.com/getlago/lago-openapi/pull/81, https://github.com/getlago/lago-openapi/pull/82, https://github.com/getlago/lago-openapi/pull/84 and https://github.com/getlago/lago-openapi/pull/85 and applies the same splitting logic for Fee resource
=> feat(fee): Add Fee resources

openapi.yaml, src/openapi.yaml, src/resources/event_estimate_fees.yaml, src/resources/plan.yaml, src/resources/plans.yaml, src/resources/webhook_public_key.yaml, src/schemas/ChargeObject.yaml, src/schemas/ChargeProperties.yaml, src/schemas/EventEstimateFeesInput.yaml, src/schemas/GroupPropertiesObject.yaml, src/schemas/Plan.yaml, src/schemas/PlanInput.yaml, src/schemas/PlanObject.yaml, src/schemas/PlansPaginated.yaml, src/schemas/_index.yaml
Follows https://github.com/getlago/lago-openapi/pull/80, https://github.com/getlago/lago-openapi/pull/81, https://github.com/getlago/lago-openapi/pull/82, https://github.com/getlago/lago-openapi/pull/84 and https://github.com/getlago/lago-openapi/pull/85 and applies the same splitting logic for organization resource
=> feat(customer): Add plan resources

openapi.yaml, src/schemas/AppliedCouponInput.yaml, src/schemas/AppliedCouponObject.yaml, src/schemas/ChargeProperties.yaml, src/schemas/CouponBaseInput.yaml, src/schemas/CouponObject.yaml, src/schemas/CustomerChargeUsageObject.yaml, src/schemas/InvoiceOneOffCreateInput.yaml, src/schemas/TaxBaseInput.yaml, src/schemas/WalletCreateInput.yaml, src/schemas/WalletObject.yaml, src/schemas/WalletTransactionCreateInput.yaml, src/schemas/WalletTransactionObject.yaml
See: https://swagger.io/docs/specification/data-models/data-types/#pattern
=> Fix OpenAPI schema paramater. Change `format` to `pattern`

.github/workflows/build-ruby-sdk.yml, generators/ruby-config.yaml
First attempt to validate Ruby SDK generation
=> misc(generator): Add configuration for ruby SDK generation

openapi.yaml, src/schemas/CreditObject.yaml
Documentation update for https://github.com/getlago/lago-api/pull/1305
=> fix(invoice): Align fees#item and credits#item seializers

openapi.yaml, src/openapi.yaml, src/resources/credit_note_estimate.yaml, src/schemas/CreditNoteEstimateInput.yaml, src/schemas/CreditNoteEstimated.yaml, src/schemas/CreditNoteObject.yaml, src/schemas/_index.yaml
Documents https://github.com/getlago/lago-api/pull/1412
=> feat(credit-note): Add estimate route before creation

openapi.yaml, src/schemas/FeeObject.yaml
Documentation update for https://github.com/getlago/lago-api/pull/1468
=> feat(fee): Expose subscription and customer ids

openapi.yaml, src/openapi.yaml, src/parameters/months.yaml, src/resources/gross_revenues.yaml, src/resources/invoiced_usages.yaml, src/resources/mrrs.yaml, src/resources/outstanding_invoices.yaml, src/schemas/GrossRevenueObject.yaml, src/schemas/GrossRevenues.yaml, src/schemas/InvoicedUsageObject.yaml, src/schemas/InvoicedUsages.yaml, src/schemas/MrrObject.yaml, src/schemas/Mrrs.yaml, src/schemas/OutstandingInvoiceObject.yaml, src/schemas/OutstandingInvoices.yaml, src/schemas/_index.yaml
Documentation update for analytics.
=> feat(analytics): Add analytics resources

openapi.yaml, src/schemas/CustomerBillingConfiguration.yaml
Add payment_provider_code to customer's billing configuration.
=> feat(psp-accounts): Add payment_provider_code

openapi.yaml, src/schemas/CustomerCheckoutUrl.yaml
This PR fixes checkout URL response. Needed informations should be nested under `customer` key.
=> fix: checkout url response structure

openapi.yaml, src/openapi.yaml, src/resources/invoice_payment_url.yaml, src/schemas/InvoicePaymentUrl.yaml
This PR adds support for payment url generation
=> feat (invoice-payment-url): add support for payment url

openapi.yaml, src/parameters/_index.yaml
Fix missing `months` parameter.
=> Fix months parameter

openapi.yaml, src/resources/fee.yaml, src/resources/fees.yaml, src/resources/wallet.yaml, src/resources/wallet_transactions.yaml, src/schemas/CreditNoteCreateInput.yaml, src/schemas/CreditNoteEstimateInput.yaml, src/schemas/CreditNoteEstimated.yaml, src/schemas/CreditNoteItemObject.yaml, src/schemas/CreditNoteObject.yaml, src/schemas/CreditObject.yaml, src/schemas/CustomerChargeUsageObject.yaml, src/schemas/CustomerUsageObject.yaml, src/schemas/EventObject.yaml, src/schemas/FeeObject.yaml, src/schemas/InvoiceMetadataObject.yaml, src/schemas/InvoiceObject.yaml, src/schemas/OrganizationBillingConfiguration.yaml, src/schemas/OrganizationObject.yaml, src/schemas/OrganizationUpdateInput.yaml, src/schemas/PlanCreateInput.yaml, src/schemas/PlanObject.yaml, src/schemas/PlanUpdateInput.yaml, src/schemas/SubscriptionObject.yaml, src/schemas/WalletObject.yaml, src/schemas/WalletTransactionCreateInput.yaml, src/schemas/WalletTransactionObject.yaml, src/schemas/WebhookEndpointObject.yaml
Fix single quote in order to avoid encoding issues
=> misc: fix single quote across project

openapi.yaml, src/schemas/CustomerCreateInput.yaml, src/schemas/CustomerObject.yaml
Change `integration_customer` param to `integration_customers`
=> misc: Change integration_customer param to integration_customers

openapi.yaml, src/schemas/CustomerBillingConfiguration.yaml
This PR updates info about values sent in payment_methods for customer_billing_configuration when setting up stripe_customer
=> feat: Add Link to Stripe payment methods

openapi.yaml, src/openapi.yaml, src/resources/invoice_retry.yaml, src/schemas/ErrorDetailObject.yaml, src/schemas/InvoiceObject.yaml, src/schemas/InvoiceObjectExtended.yaml
Added retry invoice endpoint
Added error_details into invoice payload
=> feature(anrok): add error details to invoice response

src/resources/events.yaml, src/schemas/EventsPaginated.yaml
The goal of this PR is to add GET /events endpoint
endpoint introduced in: https://github.com/getlago/lago-api/pull/2601
=> feat(events): Add GET /events/ endpoint

openapi.yaml
build openapi.yaml file not included in https://github.com/getlago/lago-openapi/pull/284
=> feat(events): update openapi.yaml file

openapi.yaml, src/resources/events.yaml, src/resources/invoices.yaml
=> fix small typo for invoice and event endpoints

openapi.yaml, src/openapi.yaml
This PR updates the API server configuration by separating the US and EU clusters into distinct URLs, improving clarity and avoiding potential issues with region-specific requests.
=> feat: Update API Server URLs to Separate US and EU Clusters

openapi.yaml, src/schemas/PlanUpdateInput.yaml
Add option cascade_updates to plan params
=> Feat: add cascade_updates option to plan params

README.md
Fixes https://github.com/getlago/lago-openapi/issues/295
=> fix: Link to contributing documentation

openapi.yaml, src/schemas/InvoiceBaseObject.yaml
This PR adds support for missing invoice status
=> ftr(tax-integrations): add description for pending status

src/resources/credit_notes.yaml, src/resources/invoices.yaml
=> feat(export credit notes): extend GET /credit notes search and filters

openapi.yaml
=> openapi: add credit notes filters to openapi.yaml file

openapi.yaml, src/schemas/SubscriptionObject.yaml
=> subscription: fix type for ending_at field

openapi.yaml, src/openapi.yaml, src/resources/credit_notes.yaml, src/resources/customers.yaml, src/resources/invoices.yaml, src/schemas/CreditNoteObject.yaml, src/schemas/CustomerBaseObject.yaml, src/schemas/CustomerCreateInput.yaml, src/schemas/FeeObject.yaml, src/schemas/InvoiceBaseObject.yaml
related to....
https://github.com/getlago/lago-api/pull/3065
https://github.com/getlago/lago-api/pull/3067
https://github.com/getlago/lago-api/pull/3094
=> feat(revshare): Add self_billed and account_type to Invoices and Customers

openapi.yaml, src/schemas/CustomerBillingConfiguration.yaml, src/schemas/CustomerIntegratrionErrorObject.yaml
=> integration(stripe): add boleto payment method

openapi.yaml, src/resources/invoices.yaml
This PR adds `progressive_billing` invoice type.
=> feat(invoice-type): Add progressive_billing invoice type

openapi.yaml, src/schemas/CustomerBillingConfiguration.yaml
=> feat(stripe): add stripe crypto to payment methods

openapi.yaml, src/schemas/CustomerBillingConfiguration.yaml
=> update openapi for Bank Transfers payment method

openapi.yaml, src/schemas/FeeObject.yaml
=> docs: fix fee types in openapi

openapi.yaml, src/schemas/WalletCreateInput.yaml, src/schemas/WalletRecurringTransactionRule.yaml, src/schemas/WalletUpdateInput.yaml
=> feat: Add Support to Expiration Wallet Rules

openapi.yaml, src/schemas/WalletTransactionObject.yaml
=> feat: add expiration_at

openapi.yaml, src/schemas/WalletRecurringTransactionRule.yaml
=> feat: add status to rules

openapi.yaml, src/schemas/InvoicePreviewInput.yaml
This PR adds support for invoice preview part 3 feature. It covers invoice preview for termination, upgrade and downgrade cases
=> feat(invoice-preview): update invoice preview docs

openapi.yaml, src/openapi.yaml, src/resources/payment_receipt.yaml, src/resources/payment_receipts.yaml, src/schemas/PaymentReceipt.yaml, src/schemas/PaymentReceiptObject.yaml, src/schemas/PaymentReceiptsPaginated.yaml
This PR adds payment receipts endpoints
=> feat(payment-receipts): Add payment receipts

openapi.yaml, src/openapi.yaml, src/resources/billing_entities.yaml, src/resources/billing_entity.yaml, src/resources/credit_notes.yaml, src/resources/customers.yaml, src/resources/invoices.yaml, src/schemas/BillingEntityCreateInput.yaml, src/schemas/BillingEntityObject.yaml, src/schemas/BillingEntityUpdateInput.yaml, src/schemas/CreditNoteObject.yaml, src/schemas/CustomerBaseObject.yaml, src/schemas/CustomerCreateInput.yaml, src/schemas/InvoiceBaseObject.yaml, src/schemas/InvoicePreviewInput.yaml, src/schemas/_index.yaml
Added info about new billing_entity endpoints, billing_entities params (will not be displayed yet as we're not enabling create and update billing_entity endpoints)
Added billing_entity_code info to the responses where it is returned
=> Feat(multientities): Add billing entity-specific endpoints

openapi.yaml, src/resources/billing_entity.yaml, src/schemas/BillingEntityObjectExtended.yaml
add applied taxes collection to the response object
=> feat(multientities): Add taxes to GET /api/v1/billing_entities/:code

openapi.yaml, src/schemas/PaymentObject.yaml
rename `external_id` as `external_customer_id`
add `lago_id`
=> fix(webhooks): payment requires action webhook payload

openapi.yaml, src/schemas/PaymentObject.yaml
- lago_id
- amount_cents
- amount_currency
=> misc: Add missing attributes to payment object

openapi.yaml, src/openapi.yaml, src/schemas/TriggeredAlertObject.yaml, src/webhooks/alert_triggered.yaml
As I documented this, I [added 2 fields here](https://github.com/getlago/lago-api/pull/3779).
=> Add `alert.triggered` webhook

openapi.yaml, src/openapi.yaml, src/resources/activity_log.yml, src/resources/activity_logs.yml, src/schemas/ActivityLog.yaml, src/schemas/ActivityLogObject.yaml, src/schemas/ActivityLogsPaginated.yaml, src/schemas/_index.yaml
GET `/activity_logs`
**Description**
> Get a collection of activity_logs 
**Files**
> `src/resources/activity_logs.yml`
`src/schemas/ActivityLogsPaginated.yaml`
------ 
GET `/activity_logs/{activity_id}` for a single activity log
**Description**
> Get a single activity_log with the provided `activity_id`
**Files**
> `src/resources/activity_log.yml`
`src/schemas/ActivityLog.yaml`
----- 
**Shared files**
> src/schemas/ActivityLogObject.yaml
=> GET endpoints for Activity Logs

openapi.yaml, src/schemas/AlertObject.yaml
https://github.com/getlago/lago-api/pull/3819
=> Add `customer_external_id` to AlertObject.yaml

openapi.yaml, src/schemas/InvoiceObject.yaml
This PR fixes a typo in the billing periods schema
=> fix billing periods typo

openapi.yaml, package-lock.json, src/schemas/WalletCreateInput.yaml, src/schemas/WalletObject.yaml, src/schemas/WalletUpdateInput.yaml
This PR adds API ref for wallet limitations by `fee_type`
=> ftr(wallet-limitations): add wallet limitations api ref

openapi.yaml, src/openapi.yaml
Related to https://github.com/getlago/lago/releases/tag/v1.31.0
=> misc(version): Bump version to 1.31.0

src/webhooks/plan_created.yaml, src/webhooks/plan_deleted.yaml, src/webhooks/plan_updated.yaml
See https://github.com/getlago/lago-api/pull/3868
=> new plan webhooks

openapi.yaml, src/openapi.yaml
A few of the tags had urls were no longer working.
=> fix(tags): Fix tags `externalDocs` URLs

openapi.yaml, src/resources/event.yaml, src/resources/event_estimate_fees.yaml, src/resources/events.yaml, src/resources/events_batch.yaml, src/schemas/CreditNotes.yaml, src/schemas/EventErrorsObject.yaml, src/schemas/EventInputObject.yaml, src/schemas/EventObject.yaml, src/schemas/EventsErrorsObject.yaml, src/schemas/_index.yaml
This PR fixes the definition for events related resources, schemas and webhooks
=> misc(event): Fix definitions

openapi.yaml, src/schemas/AppliedUsageThresholdObject.yaml, src/schemas/BillingPeriodObject.yaml, src/schemas/ChargeFilterInput.yaml, src/schemas/ChargeObject.yaml, src/schemas/InvoiceObject.yaml, src/schemas/PlanObject.yaml, src/schemas/UsageThresholdObject.yaml
This PR fixes schemas definition for objects attached to Invoice and Plan
=> misc: Improve invoice related payloads

openapi.yaml, src/schemas/AlertThresholdInput.yaml, src/schemas/EventInputObject.yaml
Fixes https://github.com/getlago/lago-openapi/issues/414
=> fix: Multiple type issues

openapi.yaml, src/resources/customer_projected_usage.yaml, src/schemas/CustomerChargeFiltersUsageObject.yaml, src/schemas/CustomerProjectedChargeGroupedUsageObject.yaml, src/schemas/CustomerProjectedChargeUsageObject.yaml, src/schemas/CustomerProjectedUsage.yaml, src/schemas/CustomerProjectedUsageObject.yaml
Revert the changes made to the `current_usage` descriptions and data.
Create new information for the `projected_usage` endpoint.
=> feat(projected-usage): Add projected usage endpoint for customer API

openapi.yaml, src/openapi.yaml, src/resources/customer_projected_usage.yaml
Missing the projected usage link on openapi.yaml file
=> misc: Update openapi.yaml file with missing page

openapi.yaml, src/resources/customer_current_usage.yaml
Fix some labels that were wrong.
=> feat(projected-usage): Fix some labels

openapi.yaml, src/resources/plan_entitlements.yaml
POST and PATCH returns list, not single items.
Added not that post will **replace** all entitlements.
=> fix: entitlements response types

openapi.yaml, src/resources/subscription.yaml, src/resources/subscriptions.yaml, src/schemas/LifetimeUsageObject.yaml, src/schemas/PlanOverridesObject.yaml, src/schemas/SubscriptionCreateInput.yaml, src/schemas/SubscriptionObject.yaml, src/schemas/SubscriptionWithCustomerObject.yaml, src/schemas/SubscriptionWithThresholdObject.yaml, src/schemas/UsageThresholdInput.yaml, src/schemas/UsageThresholdUpdateInput.yaml
There were a few outdated/missing information related to subscriptions.
This adds/updates this missing information.
=> misc: Improve subscription schemas

openapi.yaml, package-lock.json, src/resources/plan_entitlements.yaml, src/resources/subscription_entitlements.yaml, src/schemas/Entitlement/FeatureBaseInput.yaml, src/schemas/Entitlement/FeatureCreateInput.yaml, src/schemas/Entitlement/FeatureObject.yaml, src/schemas/Entitlement/FeaturePrivilegeObject.yaml, src/schemas/Entitlement/FeatureUpdateInput.yaml, src/schemas/Entitlement/PlanEntitlementObject.yaml, src/schemas/Entitlement/SubscriptionEntitlementObject.yaml, src/schemas/_index.yaml
* Tried to explain "patch" better
* Fixed required fields
* Nest input object for create/update feature
=> Update docs for entitlements

openapi.yaml, src/schemas/Entitlement/EntitlementUpdateInput.yaml
entitments update inputs must be nested under `entitlements` key.
=> fix(entitlements): update payload nesting

openapi.yaml, src/openapi.yaml, src/webhooks/subscription_updated.yaml
This PR adds the `subscription.updated` webhook.
=> feat(webhooks): Add subscription.updated endpoint
